### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_VereyaPython)

### ISSUE THREAD

**Issue by CICS-Oleg** [noskill/Vereya#3]
After updating my boost libs to 1.65.1 I faced the next problem. When I'm trying to build Vereya with -DSTATIC_BOOST=0 flag and set (BOOST_PYTHON_NAME "python3") (the only working option for me) the resulting library cannot be imported due to ImportError: dynamic module does not define module export function (PyInit_VereyaPython)

**Comment by noskill** [comment]
Please check if so file exports any PyInit_something functions
